### ISSUE TITLE
Unsafe usage of `uint`

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-libp2p#111]
`uint` is a system-sized type, yet we're using it in cross-network situations, like here - this should use a specifically sized type throughout:

https://github.com/status-im/nim-libp2p/blob/b1a34f478efe6d1212cfccecaf4dd8bf89fc2b1f/libp2p/muxers/mplex/coder.nim#L25

**Comment by dryajov** [comment]
Good point, but it's unclear what the size of the field should really be since it's not stated in the spec. The best we have is the full size of the header which is described as - `The header is an unsigned base128 varint, as defined in the protocol buffers spec`. 

The fields them self are coded as follows:

```
header = readUvarint()
flag = header & 0x07
id = header >> 3
```

So I believe that leaves 125 bits for the id, Nim's `uint` defaults to the pointer size of the architecture/runtime, so setting it explicitly to `uint64` (most architectures in use right now) should be safe enough.

**Comment by arnetheduck** [comment]
fyi base128 - that's 7 bits thus 128 values - which is how much payload fits in each varint byte. 

> The header is an unsigned base128 varint, as defined in the protocol buffers spec

if this is the spec text, then it's not specified how many bits are in the ID - it could be 1024 for all the spec cares. I'd suggest reporting it upstream - or perhaps the max id value is constrained somewhere else?

**Comment by dryajov** [comment]
> if this is the spec text, then it's not specified how many bits are in the ID - it could be 1024 for all the spec cares. I'd suggest reporting it upstream - or perhaps the max id value is constrained somewhere else?

Not to my knowledge, there aren't any constraints as to the size of the id anywhere in the spec.

**Comment by arnetheduck** [comment]
https://github.com/libp2p/specs/issues/259

**Comment by arnetheduck** [comment]
Still not fixed:

varint read is `uint`:
https://github.com/status-im/nim-libp2p/blob/5285f0d091d2f5215b5c0dd5bd3399af1afec626/libp2p/muxers/mplex/coder.nim#L36

`dataLenVarint` cast may raise Defect (if it uses uint64 range - you need to cast the DataLenSize):

https://github.com/status-im/nim-libp2p/blob/5285f0d091d2f5215b5c0dd5bd3399af1afec626/libp2p/muxers/mplex/coder.nim#L61

`id` will be `uint64` here, avoid `or` with `uint` - this  is misleading at best:
https://github.com/status-im/nim-libp2p/blob/5285f0d091d2f5215b5c0dd5bd3399af1afec626/libp2p/muxers/mplex/coder.nim#L84

**Comment by sinkingsugar** [comment]
I fixed this in #123 btw

**Comment by arnetheduck** [comment]
> I fixed this in #123 btw

write yes, readMplexVarint is still broken - https://github.com/status-im/nim-libp2p/pull/118/files#diff-b1ec9e08cf79b9ec8398347d70e030dfR37 fixes this and other varint issues
